### ISSUE TITLE
Gradle failures

### ISSUE THREAD

**Issue by superbderrick** [intbird/VideoPlayerLib#11]
Hi Mate, I was trying to build your project but It occurred some gradle failures like below, Any good way to fix it?

`A problem occurred configuring root project 'VideoPlayerLib'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find net.intbird.soft.gradle:publish-maven:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom
       - https://jcenter.bintray.com/net/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom
       - https://maven.aliyun.com/repository/google/net/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom
       - https://intbird.net/maven/snapshots/net/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom
       - https://intbird.net/maven/releases/net/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

**Comment by intbird** [comment]
https://github.com/intbird/publish-maven

I am sorry to hear that.publish-maven is a gradle plugin in my maven repo:
https://intbird.net/nexus/content/repositories/releases/intbird/soft/gradle/publish-maven/1.0.0/

**Comment by superbderrick** [comment]
Any updates?: )

**Comment by intbird** [comment]
yes
both of 
https://intbird.net/maven/releases/net/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom
https://intbird.net/maven/releases/intbird/soft/gradle/publish-maven/1.0.0/publish-maven-1.0.0.pom

**Comment by superbderrick** [comment]
Great It working well thanks 👍 :)
